apiVersion: v1
kind: Secret
metadata:
  name: airbnb-serving-secret
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: "your_uri"
  MLFLOW_TRACKING_USERNAME: "your_username"
  MLFLOW_TRACKING_PASSWORD: "your_password"
  MODEL_RUN_ID: "b03526c7c67540f9a5566c3277b0f150"
